#!/usr/bin/env python3
"""Generate CODE_MAP.md: every function of src/chuchu.s, grouped by layer and
module, with its original address and the first sentence of its ;; header,
followed by the named variables and tables.

  python tools/codemap.py            writes CODE_MAP.md at the project root

Run it again after renaming labels or editing headers (tools/rename.py)."""
import os, re, sys, struct, subprocess, tempfile, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import xref  # noqa: E402

SRC = os.path.join(ROOT, 'src', 'chuchu.s')
OUT = os.path.join(ROOT, 'CODE_MAP.md')

# The Pure C linker keeps every .C file in one piece and in link order, so the
# address ranges below follow the source files of the original game.
LAYERS = [
    (0x00000, 'System layer (GodLib)',
     'The Reservoir Gods library: DMA audio mixer, YM sound chip, keyboard processor (IKBD), '
     'MFP timers, VBL, video modes, memory, files, CHUCHU.LNK archive, Pack-Ice depacker, '
     'screen grabber, machine detection.'),
    (0x049a6, 'Game modules (1)',
     'AI, arrows, demo, puzzle panel, mice, board cells, timers, controls and options menus, '
     'AI path maps, front end, round life cycle, save file, spawners, input.'),
    (0x0a190, 'Game modules (2)',
     'Application state machine, cats, level bank, game init/exit, players, cursors, random, '
     'rockets, roulette (spinner), sound effects and music.'),
    (0x0d4bc, 'Render modules (1)',
     'Atari intro, front-end screens, fonts, fades, arrow / board / mouse / cat drawing, level select.'),
    (0x10960, 'Render modules (2)',
     'Frame rendering, HUD, results and congratulations screens, screens and buffers, roulette '
     'graphics, starfield, dirty-tile restore.'),
    (0x14780, 'Graphics library and C runtime',
     'Title rocket, sprite and 4-plane graphics routines, blitter helpers, Pure C runtime '
     '(strings, memory, long and floating-point arithmetic, GEMDOS/XBIOS calls).'),
]


def symbols():
    """name (22 chars max) -> (section, offset in that section), from a build with symbols."""
    tmp = tempfile.mktemp(suffix='.prg')
    subprocess.run([os.environ.get('VASM', 'vasmm68k_mot'), '-Ftos', '-no-opt', '-m68000', '-quiet',
                    '-o', tmp, SRC], check=True, capture_output=True)
    raw = open(tmp, 'rb').read()
    os.remove(tmp)
    _, tl, dl, bl, sl = struct.unpack('>HIIII', raw[:18])
    st = raw[28 + tl + dl:28 + tl + dl + sl]
    out, i = {}, 0
    while i < len(st):
        nm = st[i:i + 8]
        typ, val = struct.unpack('>HI', st[i + 8:i + 14])
        i += 14
        if typ & 0x48 == 0x48:
            nm += st[i:i + 14]
            i += 14
        out[nm.rstrip(b'\0').decode('latin1')] = val
    return out, tl, dl


def header(lines, i):
    """;; block just above line i, as a list of lines without the ';; ' prefix."""
    h = []
    j = i - 1
    while j >= 0 and lines[j].startswith(';;'):
        h.insert(0, lines[j][2:].strip())
        j -= 1
    return h


def summary(h, limit=230):
    text = ''
    for l in h:
        if not l:
            break
        text = (text + ' ' + l).strip()
        if text.endswith('.') and len(text) > 40:
            break
    text = re.sub(r'\s+', ' ', text)
    if len(text) > limit:
        cut = text[:limit]
        text = cut[:cut.rfind(' ')] + ' ...'
    return text.replace('|', '\\|')


def content(lines, i):
    """Short description of undocumented data: its text, or its first values."""
    first = lines[i + 1].strip() if i + 1 < len(lines) else ''
    m = re.match(r'^dc\.b\s+"([^"]*)"', first)
    if m:
        return 'text "%s"' % m.group(1).replace('|', '\\|')
    m = re.match(r'^ds\.b\s+(\d+)', first)
    if m:
        return '%s bytes' % m.group(1)
    if first.startswith(('dc.', 'even')):
        first = re.sub(r'\s+', ' ', first)
        return '`%s`' % (first if len(first) < 70 else first[:66] + ' ...')
    return ''


def main():
    lines, bodies, strings = xref.parse()
    info, callers = xref.analyse(lines, bodies)
    syms, tl, dl = symbols()
    funcs = []
    for name, (a, b) in bodies.items():
        addr = syms.get(name[:22])
        funcs.append((addr if addr is not None else 1 << 30, name, a))
    funcs.sort()

    md = ['# Code map', '',
          'Every function of `src/chuchu.s`, in the order of the original program, grouped by layer and '
          'module. The address is the offset in the original program (TEXT section); the description is '
          'the first sentence of the `;;` block written above the function in the source, where the '
          'full description, parameters and return values are.', '',
          'Generated by `python tools/codemap.py` (run it again after renaming). '
          'See `GAME_LOGIC.md` for how the game works and `src/settings.s` for the values you can change.', '']
    layer_of = []
    for addr, name, a in funcs:
        k = max(i for i, l in enumerate(LAYERS) if addr >= l[0]) if addr < (1 << 30) else len(LAYERS) - 1
        layer_of.append(k)

    # table of contents
    md += ['## Contents', '']
    counts = collections.Counter(layer_of)
    for k, (start, title, _) in enumerate(LAYERS):
        end = LAYERS[k + 1][0] if k + 1 < len(LAYERS) else tl
        md.append('- [%s](#%s) : $%05x-$%05x, %d functions' % (
            title, re.sub(r'[^a-z0-9 -]', '', title.lower()).replace(' ', '-'), start, end - 1, counts[k]))
    md += ['- [Variables and tables](#variables-and-tables)', '',
           '%d functions in total. Addresses are those of the original executable; '
           'the OPT_* optimisations add a few functions (`Blit_*`) that exist only in optimised builds.' % len(funcs), '']

    for k, (start, title, desc) in enumerate(LAYERS):
        md += ['## %s' % title, '', desc, '']
        groups = collections.OrderedDict()
        for (addr, name, a), lk in zip(funcs, layer_of):
            if lk == k:
                groups.setdefault(name.split('_')[0], []).append((addr, name, a))
        for mod, items in groups.items():
            md += ['### %s' % mod, '', '| Address | Function | What it does |', '|---|---|---|']
            for addr, name, a in items:
                ad = '$%05x' % addr if addr < (1 << 30) else '(opt)'
                md.append('| %s | `%s` | %s |' % (ad, name, summary(header(lines, a))))
            md.append('')

    # variables and tables
    md += ['## Variables and tables', '',
           'Named data (`D` = initialised data, `B` = zeroed BSS). Offsets are from the start of '
           'their section. Unnamed ones keep their `D_xxxxx` / `B_xxxxx` address label.', '',
           '| Section | Offset | Name | What it holds |', '|---|---|---|---|']
    sect = None
    rows = []
    for i, l in enumerate(lines):
        m = re.match(r'^\s+section\s+(\w+)', l)
        if m:
            sect = m.group(1)
            continue
        if sect not in ('data', 'bss'):
            continue
        m = re.match(r'^([A-Za-z_]\w*):', l)
        if not m or re.match(r'^[DB]_[0-9a-f]{5}$', m.group(1)):
            continue
        name = m.group(1)
        off = syms.get(name[:22])      # data/bss symbols are relative to their section
        h = summary(header(lines, i), 200)
        if not h:
            h = content(lines, i) or ('only in optimised builds' if off is None else '')
        rows.append((sect, off, name, h))
    for sect, off, name, h in rows:
        md.append('| %s | %s | `%s` | %s |' % ('D' if sect == 'data' else 'B',
                                               '(opt)' if off is None else '$%05x' % off, name, h))
    md.append('')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(md))
    print('CODE_MAP.md : %d functions, %d named variables/tables' % (len(funcs), len(rows)))


if __name__ == '__main__':
    main()
